### ISSUE TITLE
Improve swift concurrency throughout the SDK

### ISSUE THREAD

**Issue by etoledom** [Automattic/Gravatar-SDK-iOS#130]
We can use `-strict-concurrency=complete` flag to check the overall implementation:

```swift
.target(
    name: "Gravatar",
    swiftSettings: [
        .unsafeFlags(["-strict-concurrency=complete"])
    ]
),
```

or also

```swift
.target(
    name: "Gravatar",
    swiftSettings: [
        .enableUpcomingFeature("StrictConcurrency")
    ]
),
```

**Comment by pinarol** [comment]
I will add some subtasks here:

- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/156
- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/157
- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/166
- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/158
- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/159
- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/160
- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/161
- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/162
- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/163
- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/164
- [x] https://github.com/Automattic/Gravatar-SDK-iOS/issues/165
