### ISSUE TITLE
Add a new option to the ActivityIndicatorType

### ISSUE THREAD

**Issue by pinarol** [Automattic/Gravatar-SDK-iOS#153]
Add a new option to the ActivityIndicatorType.

Animation will look like this:

https://video.wordpress.com/v/jIEjJ7Ri

Color1: #FFFFFF
Color2: #DADADA

I think the colors can be customizable.

I don't know the proper name for this animation yet but maybe "ghostAnimation", or "colorAnimation" ?

> case colorAnimation(color1: UIColor?, color2: UIColor?):

or, maybe it's better if we allow to pass an optional array and not limit the number of colors. If nil, we use our own colors:

> case colorAnimation(colors: [UIColor]?):

This will be the default for the profile card, but the 3rd party devs should be able to set a different ActivityIndicatorType.

**Comment by etoledom** [comment]
@pinarol - I guess this is closed by https://github.com/Automattic/Gravatar-SDK-iOS/pull/225 ?

**Comment by pinarol** [comment]
This is actually a different thing which is just for the avatar download but I think we can still close it because it's not very convenient to use an opaque background activity loader for the avatar. Let's close this for now and come back to it where needed.
