### ISSUE TITLE
[Concurrency] Fix `ImageCache.cache` issue

### ISSUE THREAD

**Issue by pinarol** [Automattic/Gravatar-SDK-iOS#157]
There's an error related to ImageCache.cache usage.

We can make this change to fix it.

<img width="1280" alt="Screenshot 2024-04-03 at 12 33 21" src="https://github.com/Automattic/Gravatar-SDK-iOS/assets/5032900/dfccc393-0def-4254-874e-b9f95c008b60">

The whole diff is here: https://github.com/Automattic/Gravatar-SDK-iOS/pull/136/files

**Comment by etoledom** [comment]
I do have one concern with this:

`NSCache` is a class anyway, so it could bring troubles.

Apple docs says it's thread-safe, but with a catch. 
The `Section 2: Cache quake details` explains the details https://developer.apple.com/tutorials/app-dev-training/caching-network-data

I guess we can make it work as described in the mentioned tutorial.
