### ISSUE TITLE
[Concurrency] Make ImageProcessingMethod Sendable

### ISSUE THREAD

**Issue by pinarol** [Automattic/Gravatar-SDK-iOS#163]
To achieve this, I made `ImageProcessor` conform to `Actor`. I think this is a good candidate to be an actor. And awaiting on the process() method is reasonable. 

<img width="990" alt="Screenshot 2024-04-03 at 13 00 51" src="https://github.com/Automattic/Gravatar-SDK-iOS/assets/5032900/6e8c367a-f15a-4ca5-881a-db559f90f8f0">

Full diff is here: https://github.com/Automattic/Gravatar-SDK-iOS/pull/136/files

**Comment by etoledom** [comment]
I believe this has been fixed by https://github.com/Automattic/Gravatar-SDK-iOS/pull/232

Closing for now
