### ISSUE TITLE
Choosing a minimum supported version of iOS

### ISSUE THREAD

**Issue by andrewdmontgomery** [Automattic/Gravatar-SDK-iOS#31]
At the moment, we have defined our SDK Package with `iOS 15` as the minimum we support.  Should we go lower?  I'm tempted to be aggressive about this, and add support for versions older than iOS 15 only if needed.  But I'm not sure.

That raises a related question that we'll face down the road: I wonder how many versions of iOS we'll want to support?  I suppose that will depend.  A spot check of a few other iOS libraries looked like using `iOS 11` as a minimum may be common.  But these are for libraries that have been around for a while:

- [Alamofire](https://github.com/Alamofire/Alamofire/blob/master/Package%40swift-5.9.swift)
- [Firebase](https://github.com/firebase/firebase-ios-sdk/blob/main/Package.swift)
- [SDWebImage](https://github.com/SDWebImage/SDWebImage/blob/master/Package.swift) (iOS 9!)

**Comment by pinarol** [comment]
Just cleaning up some old issues and I saw this one. I believe we settled on iOS 15 for now. So I'll go ahead and close this issue.
