### ISSUE TITLE
Quick Editor: Use PHPickerViewController

### ISSUE THREAD

**Issue by pinarol** [Automattic/Gravatar-SDK-iOS#381]
Let's look into using PHPickerViewController for picking the image.

PHPickerViewController:
- Designed with privacy in mind; it does not require full access to the photo library.
- The user selects only the photos or videos they want to share with the app, and the app only gets access to those specific items.

**Comment by etoledom** [comment]
We only can start using `PHPickerViewController` when we implement a custom image cropper, as it doesn't offer this option.

**Comment by pinarol** [comment]
Good point. 👍

**Comment by pinarol** [comment]
Another possibility: Allowing to inject the whole image picker together with the cropper 🤔. So in case other repos already have PHPickerViewController + their own cropper, they can continue using it. This way at least we wouldn't be lowering their existing privacy level.
