### ISSUE TITLE
Allow to pass a delegate to `ProfileViewController`

### ISSUE THREAD

**Issue by wzieba** [Automattic/Gravatar-SDK-iOS#383]
### Current behavior

SDK consumer that uses `ProfileViewController` is not able to pass a `delegate` to apply on click actions on a profile card.

### Expected behavior

It is possible to make profile card interactive when using `ProfileViewController`.

### Workaround

For my case of using `SwiftUI` and `UIViewControllerRepresentable`, @pinarol suggested a solution with copying source code of `ProfileViewController` and `DemoProfileViewsViewController` from this repository and update `ProfileViewController#configuration#didSet` to apply a delegate.

This works fine, but requires SDK consumer to copy boilerplate code, that I'd rather prefer removed from my codebase.
Internal communication: p1725439264859349-slack-C06FRGK6Y5R

**Comment by pinarol** [comment]
Thanks for the report!

ProfileViewController can conform to ProfileViewDelegate and handle the tap events internally so no one else needs to.
