### ISSUE TITLE
Send Accept-Language header

### ISSUE THREAD

**Issue by pinarol** [Automattic/Gravatar-SDK-iOS#399]
We should send Accept-Language header in the REST API calls like:

> Accept-Language: en-US, fr-CA, es-ES

It seems to me like we can take the values from `NSLocale.preferredLanguages`.

**Comment by andrewdmontgomery** [comment]
After investigating, it looks like a simple version of that header is already included by default.  PR #416 adds a more comprehensive version of this header.  See that PR for details.
