### ISSUE TITLE
QE: SwiftUI profile card empty space issue

### ISSUE THREAD

**Issue by pinarol** [Automattic/Gravatar-SDK-iOS#478]
@Luchadores reported:

> When the user doesn’t have any information, we should decrease the space between the name and the link (View profile) as per the design before.

![Image](https://github.com/user-attachments/assets/587487f8-c494-4e60-be5e-dbc180938d4c)

**Comment by pinarol** [comment]
I am able to reproduce:

<img width=300 src="https://github.com/user-attachments/assets/e9561d03-478a-4f96-b325-2c8ce3481a29"/>

**Comment by etoledom** [comment]
This is done on the UIKit ProfileViews. Sad that we can't use them (yet?) on SwiftUI side 🤦
